### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: |-
      Codes d’erreur pour les fonctions personnalisées. Les codes d’erreur s’affichent dans la cellule qui a appelé la fonction.

      Les messages d’erreur personnalisés s’affichent en plus de ces codes d’erreur. Les messages personnalisés s’affichent dans le menu indicateur d’erreur, accessible en plaçant le curseur sur l’indicateur d’erreur sur chaque cellule avec une erreur.
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: "Ce code d’erreur indique que la fonction utilisée est divisée par zéro ou des cellules vides. Un message d’erreur personnalisé ne peut pas être utilisé. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: "Ce code d’erreur indique qu’il existe une faute de frappe dans le nom de la fonction. Notez que ce code d’erreur est pris en charge en tant qu’erreur de saisie d’une fonction personnalisée, mais pas en tant qu’erreur de sortie de fonction personnalisée. Un message d’erreur personnalisé ne peut pas être utilisé. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: "Ce code d’erreur indique qu’il y a un problème avec un numéro dans la fonction. Un message d’erreur personnalisé ne peut pas être utilisé. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: "Ce code d’erreur indique que la fonction fait référence à une cellule non valide. Notez que ce code d’erreur est pris en charge en tant qu’erreur de saisie d’une fonction personnalisée, mais pas en tant qu’erreur de sortie de fonction personnalisée. Un message d’erreur personnalisé ne peut pas être utilisé. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: "Ce code d’erreur indique qu’une valeur dans la fonction est d’un type de données incorrect. Un message d’erreur personnalisé peut être utilisé en plus du code d’erreur, si vous le souhaitez. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: "Ce code d’erreur indique que la fonction ou le service n’est pas disponible. Un message d’erreur personnalisé peut être utilisé en plus du code d’erreur, si vous le souhaitez. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: "Ce code d’erreur indique que les plages de la fonction ne se croisent pas. Un message d’erreur personnalisé ne peut pas être utilisé. \\[[Ensemble d’API\_: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\\]"
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'